# CS 109A Data Science: Project
**Harvard University**<br>
**Fall 2016**<br>
**Team member:** Becerra, Fernando; Mayo, Andrew Wayne; Ding, Yi; Cao, Xinrui<br>
**Project topic:** Predicting Seizures and Epilepsy

In [1]:
import numpy as np
import pandas as pd
import scipy as sp
import time
from scipy.stats import mode
from sklearn import linear_model
import sklearn.linear_model as sk
import matplotlib
import matplotlib.pyplot as plt
from sklearn import discriminant_analysis
import sklearn.discriminant_analysis as da
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn import preprocessing
from sklearn.preprocessing import PolynomialFeatures
%matplotlib inline

In [104]:
# Read in the data set
epil = pd.read_csv('Data/Updated seizure csv/epil.csv', delimiter=',')
epil.head()

Unnamed: 0  y      trt  base  age  V4  subject  period     lbase      lage
0           1  5  placebo    11   31   0        1       1 -0.756354  0.114204
1           2  3  placebo    11   31   0        1       2 -0.756354  0.114204
2           3  3  placebo    11   31   0        1       3 -0.756354  0.114204
3           4  3  placebo    11   31   1        1       4 -0.756354  0.114204
4           5  3  placebo    11   30   0        2       1 -0.756354  0.081414

In [105]:
# Change objects into numerics
list1 = np.where(epil['trt']=='progabide')
list2 = np.where(epil['trt']!='progabide')
for ind in list1:
    epil['trt'][ind] = 1

for ind in list2:
    epil['trt'][ind] = 0
sum(epil['trt'])

epil.head()
x = epil.iloc[:, 2:9]   # 7 covariates
y = epil.iloc[:, -9]    # count of seizure for a 2-week period.

/Users/Jessica/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/Jessica/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [106]:
# Fit a Linear Discriminant Analysis (LDA)
LDA = da.LinearDiscriminantAnalysis()
model_LDA = LDA.fit(x, y.astype(int))
print 'Accuracy of LDA:', LDA.score(x,y.astype(int))

Accuracy of LDA: 0.317796610169


In [107]:
# Fit a multinomial logistic regression model
logitm = sk.LogisticRegression(C = 1000000, penalty="l1")
logitm.fit(x, y)

print 'Accuracy of multinomial logistic regression:', logitm.score(x,y.astype(int))

Accuracy of multinomial logistic regression: 0.338983050847


- **Each subject is observed in 4 period, should we combine them into 1 longer period and build model on top of that?** 

In [164]:
# Read in data set UKDA-2024-tab
UKDA_2024_tab = pd.read_table('Data/1958 NCDS/UKDA-2024-tab/tab/warnock.tab')
UKDA_4992_tab = pd.read_table('Data/1958 NCDS/UKDA-4992-tab/tab/ncds37yearsurveydata.tab')
UKDA_5567_tab1 = pd.read_table('Data/1958 NCDS/UKDA-5567-tab/tab/ncds5cmi.tab')
UKDA_5567_tab2 = pd.read_table('Data/1958 NCDS/UKDA-5567-tab/tab/ncds5mc.tab')
UKDA_5578_tab = pd.read_table('Data/1958 NCDS/UKDA-5578-tab/tab/ncds6.tab')
UKDA_6137_tab = pd.read_table('Data/1958 NCDS/UKDA-6137-tab/tab/ncds_2008_followup.tab')


In [102]:
list_epil = np.where(UKDA_2024_tab['NW0284'] == 2)    # Health problem Epilepsy  
list_epil2 = np.where(UKDA_2024_tab['NW0285'] == 2)    # Health problem Epilepsy 
print list_epil, list_epil2

(array([  3,  94, 163, 295, 381]),) (array([382]),)


In [125]:
np.where(UKDA_4992_tab['nss2127'] =="6")    ## long-term problem: Epilepsy

(array([  61,  495,  592,  862,  983, 1688]),)

In [134]:
ever_suffer = np.where(UKDA_5567_tab1['n503930'] =="1")
only_pregnant = np.where(UKDA_5567_tab1['n503930'] =="2")
suffer_last_12_month = np.where(UKDA_5567_tab1['n503931']=='1')
seen_doctor_last_12_month = np.where(UKDA_5567_tab1['n503932']=='1')
print ever_suffer  # Ever suffered yes
print only_pregnant   # Only when pregnant
print suffer_last_12_month   # subject having seizure during the last 12 month
print seen_doctor_last_12_month   # subject went to the doctor's during the last 12 month

(array([   20,    53,    90,    92,    95,   350,   505,   561,   581,
         786,   842,   872,   906,   930,  1005,  1101,  1103,  1104,
        1167,  1310,  1386,  1411,  1422,  1555,  1562,  1831,  2061,
        2062,  2063,  2082,  2128,  2225,  2332,  2346,  2409,  2542,
        2549,  2582,  2588,  2663,  2753,  3077,  3209,  3253,  3259,
        3289,  3306,  3318,  3383,  3560,  3610,  3826,  3900,  3931,
        4139,  4292,  4511,  4523,  4678,  4780,  4813,  4885,  4924,
        5056,  5058,  5216,  5287,  5584,  5643,  5702,  5940,  5944,
        5995,  6017,  6147,  6232,  6297,  6362,  6371,  6573,  6599,
        6603,  6645,  6689,  6807,  6835,  6939,  6941,  7028,  7043,
        7063,  7190,  7266,  7354,  7475,  7575,  7709,  7717,  7754,
        7846,  7966,  7997,  8254,  8273,  8359,  8472,  8510,  8681,
        8799,  8803,  8885,  8977,  8982,  9191,  9280,  9293,  9375,
        9423,  9458,  9506,  9615,  9824,  9831,  9868,  9915, 10049,
       10076, 10129

In [152]:
mother_epil_ever = np.where(UKDA_5567_tab2['n516623'] == 1)   # mother who had epil before
print mother_epil_ever

age_first_attack = np.where(UKDA_5567_tab2['n516624'] != 0)    # age first attacked by epil
print age_first_attack

age_last_attack = np.where(UKDA_5567_tab2['n516626'] != 0)    # age last attacked by epil
print age_last_attack

(array([ 371, 1363, 1438, 1565, 1793, 1925, 2360, 3295, 3629, 3780, 3977,
       4234]),)
(array([ 371, 1363, 1438, 1565, 1793, 1925, 3780, 3977, 4234]),)
(array([ 371, 1363, 1438, 1565, 1793, 1925, 2360, 3295, 3629, 3780, 3977]),)


In [167]:
seizure_ever = np.where(UKDA_5578_tab['fit'] == 1)   # CM ever had fits,convulsions,epilepsy
print seizure_ever
len(UKDA_5578_tab)

(array([  303,   355,   421,   436,   764,   765,  1049,  1101,  1102,
        1103,  1165,  1202,  1263,  1276,  1560,  1568,  1725,  1729,
        1836,  1845,  1891,  1956,  2005,  3390,  3401,  3429,  3840,
        3885,  3916,  4016,  4046,  4090,  4408,  4416,  4424,  4494,
        4528,  4547,  4564,  4577,  4872,  4913,  5021,  5041,  5387,
        5427,  5494,  5617,  5624,  5675,  5745,  5788,  5811,  5813,
        5826,  6403,  6543,  6545,  6552,  6571,  6576,  6618,  7229,
        7266,  7275,  7329,  7358,  7410,  7599,  7673,  7679,  7706,
        7717,  7719,  7751,  7769,  7809,  7836,  7918,  8201,  8204,
        8219,  8255,  8301,  8419,  8432,  8459,  8494,  8523,  8612,
        8656,  9755,  9794,  9830,  9876,  9878,  9908,  9931, 10772,
       10809, 10857, 10879, 10882, 10884, 10915, 10922, 10966, 10992,
       11004, 11014, 11027, 11069, 11129, 11212, 11246, 11251, 11252,
       11320, 11338]),)


11419

In [168]:
seizure_ever1 = np.where(UKDA_6137_tab['N8KHPB04'] == 1)   # "KHLPRB4" CM ever had fits,convulsions,epilepsy
print seizure_ever1

medicat1 = np.where(UKDA_6137_tab['N8FITSMD'] == 1) # "fitsmed" reg medicat for convulsion/fits/epileptic seizures
print medicat1

seizure_ever2 = np.where(UKDA_6137_tab['N8XKHP04'] == 1) # "Proxy" CM ever had fits,convulsions,epilepsy
print seizure_ever2

medicat2 = np.where(UKDA_6137_tab['N8XFITMD'] == 1) # "proxy" reg medicat for convulsion/fits/epileptic seizures
print medicat2

len(UKDA_6137_tab)

(array([ 685,  794,  855,  936,  937, 1012, 1330, 1335, 1575, 1776, 2191,
       2409, 2454, 2473, 2486, 2522, 2874, 2926, 3185, 3253, 3276, 3402,
       3493, 3553, 3755, 3761, 3869, 3892, 4335, 4430, 4455, 4579, 4722,
       4761, 5290, 5359, 5408, 5414, 5438, 5669, 5685, 5898, 5995, 6071,
       6294, 6416, 6582, 6616, 6795, 6865, 7025, 7038, 7071, 7142, 7453,
       7470, 7475, 7564, 7645, 7667, 7687, 7716, 7719, 7773, 7823, 7888,
       8000, 8051, 8108, 8465, 8570, 8596, 8602, 8651, 8790, 8837, 9167,
       9247, 9367, 9380, 9630]),)
(array([ 794,  936,  937, 1012, 1330, 1335, 1575, 1776, 2191, 2409, 2473,
       2486, 2522, 2874, 2926, 3185, 3253, 3276, 3402, 3493, 3553, 3761,
       3869, 3892, 4335, 4430, 4455, 4579, 4722, 4761, 5359, 5414, 5438,
       5669, 5685, 5898, 5995, 6071, 6294, 6416, 6582, 6616, 7025, 7038,
       7142, 7453, 7470, 7475, 7564, 7645, 7667, 7687, 7716, 7719, 7773,
       7888, 8000, 8051, 8465, 8570, 8596, 8602, 8790, 8837, 9167, 9247,
       9367, 93

9790